// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senai.InLock.CodeFisrt.WebApi.Manha.Contexts;

namespace Senai.InLock.CodeFisrt.WebApi.Manha.Migrations
{
    [DbContext(typeof(InLockContext))]
    partial class InLockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Senai.InLock.CodeFisrt.WebApi.Manha.Domains.EstudiosDomain", b =>
                {
                    b.Property<int>("EstudioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstudioNome")
                        .IsRequired()
                        .HasColumnName("NomeEstudio")
                        .HasColumnType("varchar(250)");

                    b.HasKey("EstudioId");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("Senai.InLock.CodeFisrt.WebApi.Manha.Domains.JogosDomain", b =>
                {
                    b.Property<int>("JogoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<int>("EstudioId");

                    b.Property<string>("NomeJogo")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<decimal>("Valor");

                    b.HasKey("JogoId");

                    b.HasIndex("EstudioId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Senai.InLock.CodeFisrt.WebApi.Manha.Domains.JogosDomain", b =>
                {
                    b.HasOne("Senai.InLock.CodeFisrt.WebApi.Manha.Domains.EstudiosDomain", "Estudio")
                        .WithMany("Jogos")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
