CREATE DATABASE DatabaseFirst.Senatur;
GO

USE DatabaseFirst.Senatur;
GO

CREATE TABLE Pacotes(
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(250) UNIQUE NOT NULL,
	Descricao TEXT NOT NULL,
	DataId DATE NOT NULL, 
	DataVolta DATE NOT NULL,
	Valor DECIMAL(7,2) NOT NULL,
	Ativo BIT NOT NULL,
	NomeCidade VARCHAR(250) NOT NULL   
);

CREATE TABLE Usuarios(
	Id INT IDENTITY PRIMARY KEY,
	Email VARCHAR(250) UNIQUE NOT NULL,
	Senha VARCHAR(250) NOT NULL,
	TipoUsuario VARCHAR(250) NOT NULL
);