CREATE DATABASE InLockGames;
GO

USE InLockGames;
GO

--- Table Create
CREATE TABLE Estudios (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE Jogos (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Nome VARCHAR(250) UNIQUE NOT NULL,
	Descricao TEXT NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor DECIMAL NOT NULL,
	EstudioId INT FOREIGN KEY REFERENCES Estudios(Id)
);

CREATE TABLE Usuarios (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Email VARCHAR(250) UNIQUE NOT NULL,
	Senha VARCHAR(250) NOT NULL,
	TipoUsuario VARCHAR(250) NOT NULL
);